language: php

sudo: false

php:
  - 7.4

matrix:
  include:
    - php: 7.0
      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml" CHECK_CS=true

install:
  # install composer dependencies
  - composer install --prefer-source
